all:
	javac Hello.java -classpath softIV/tut2018informationQuantity
	javac Frequencer.java -classpath softIV/tut2018informationQuantity
	javac InformationEstimator.java -classpath softIV/tut2018informationQuantity
	javac TestCase.java -classpath softIV/tut2018informationQuantity
run:
#	java -classpath softIV/tut2018informationQuantity/s4.B161303/Hello
#	java -classpath softIV/tut2018informationQuantity/s4.B161303/Frequencer
#	java -classpath softIV/tut2018informationQuantity/s4.B161303/InformationEstimator
	java -classpath softIV/tut2018informationQuantity/s4.B161303/TestCase
